apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dashboard.yaml
  #- designer.yaml

  - integrationruntime.yaml
  - emptyuser-configuration.yaml
  - serverconf
  - sample-configmap.yaml
