apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - kafka-connect.yaml  
  - datagen.yaml
  - kafka-connect-topics.yaml
 # - https://raw.githubusercontent.com/IBM/event-automation-demo/main/install/eventstreams/templates/05-kafkaconnect-topics.yaml
  

  - mq-connector-topic.yaml
  - mq-source-connector.yaml
  
namespace: cp4i

patches:
  - target:
      version: v1beta2
      kind: KafkaTopic
    path: cluster-name-patch.yaml

