kind: ConfigMap
apiVersion: v1
metadata:
  name: sample-qm2-configmap
data:
  tls.mqsc: |
    DEFINE QLOCAL('ALPHA.QUEUE1') DEFPSIST(YES) REPLACE 
    DEFINE QLOCAL('ALPHA.QUEUE2') DEFPSIST(YES) REPLACE
    DEFINE QLOCAL('ALPHA.QUEUE3') DEFPSIST(YES) REPLACE
    DEFINE QLOCAL('ALPHA.QUEUE4') DEFPSIST(YES) REPLACE
    DEFINE CHANNEL(HAQMCHL) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH(HAQMCHL) TYPE(BLOCKUSER) USERLIST('nobody') ACTION(ADD)