apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator/subscriptiopn.yaml
  - https://raw.githubusercontent.com/thomas-mattsson/s2i-ace/main/tekton/tasks/s2i-ace-overlay-task.yaml
  - https://raw.githubusercontent.com/thomas-mattsson/s2i-ace/main/tekton/tasks/s2i-ace-task.yaml