apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate these config maps from mqsc files to support
# syntax hignlighting in tooling.
configMapGenerator:
  - name: native-ha-qm-configmap
    files:
      - qm-config/tls.mqsc
      - qm-config/mq.ini

generatorOptions:
  disableNameSuffixHash: true

resources: 

  - qm.yaml
  - sni-route.yaml

  - tls/ca-ss-issuer.yaml
  - tls/nativeha-certificate.yaml
  - tls/queue-manager-certificate.yaml