apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../components/flink/variants/cloudprovider/odf
# - ../../../../components/flink/variants/nonprod

resources:
- ../../../../components/flink/base