apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate these config maps from mqsc files to support
# syntax hignlighting in tooling.
configMapGenerator:
  - name: wellknown-cert-qm-configmap
    files:
      - qm-config/tls.mqsc
      - qm-config/mq.ini

generatorOptions:
  disableNameSuffixHash: true

resources:
 
  # Resources for QM using certificate from LetsEncrypt

  - qm.yaml
  - sni-route.yaml

  - tls/mq-server-certificate.yaml
  - tls/letsencrypt-chain.yaml